### ISSUE TITLE
Request for datasets（MITOS-ATYPIA-14）

### ISSUE THREAD

**Issue by china-suli** [Bcai0797/SDN#1]
Hello, author.
I recently read your new paper titled "Self-supervised Digital Histopathology Image Disentanglement for Arbitrary Domain Stain Transfer." I am very interested in your article. You have provided a link to the public dataset ([MITOS-ATYPIA-14](https://mitos-atypia-14.grand-challenge.org/)), but the dataset is now incomplete and I would be grateful if you could send me a copy of the complete dataset.

**Comment by Bcai0797** [comment]
Thanks for your attention! Due to the network and the size of the dataset, we uploaded the copy of MITOS-ATYPIA-14 to [BaiduYun](https://pan.baidu.com/s/1AUG3wkmTF7NA0hjAJ874vg?pwd=7566). Hope it helps!
